alias _='sudo'
alias apb='ansible-playbook'
alias apk='ansible-playbook -K'
alias cd..='cd ..'
alias cls='clear'
alias dc='cd'
alias dcup='docker-compose up -d'
alias dcdn='docker-compose down'
alias dd='dd status=progress'
alias diff='colordiff'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias em='emacs -nw'
alias fgrep='fgrep --color=auto'
alias glog='git log --oneline --graph --color --all --decorate'
alias gpull='git pull'
alias gpush='git push'
alias grep='grep --color=auto'
alias gti='git'
alias l='ls -CF'
alias la='ls -A'
alias less='less -R'
alias ll='ls -l'
alias ls='ls --color=auto'
alias nethack-online='ssh nethack@nethack.alt.org ; clear'
alias ssh-init='eval "$(ssh-agent -s)"'
alias ssh-init2='ssh-add ~/.ssh/id_rsa'
#alias tmux='tmux -2'
alias tron-online='ssh sshtron.zachlatta.com ; clear'
alias vdir='vdir --color=auto'